apiVersion: apps/v1
kind: Deployment
metadata:
  name: voucher-management-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: voucher-management-app
  template:
    metadata:
      labels:
        app: voucher-management-app
    spec:
      containers:
        - name: voucher-management-app
          image: public.ecr.aws/s6y5a7e8/voucher-app:VERSION
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-secret
                  key: db_password

---
apiVersion: v1
kind: Service
metadata:
  name: springboot-k8s-service
spec:
  selector:
    app: voucher-management-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8081
  type: NodePort
